from datetime import datetime
from unittest import mock

from gpw_scraper.llm import LLMClientManaged, ModelManager
from gpw_scraper.schemas.espi import EspiLLMSummary
from gpw_scraper.scrapers.pap import EspiEbiPapScraper


async def test_espi_ebi_pap_scraper_scrape(pap_test_client):
    expected = {
        "https://espiebi.pap.pl/node/560617": {
            "type": "ESPI",
            "title": "Podsumowanie kosztów VI Programu Emisji Obligacji",
            "description": "LLM_DESCRIPTION",
            "company": "PCC EXOL SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560617",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 23, 9),
        },
        "https://espiebi.pap.pl/node/560616": {
            "type": "ESPI",
            "title": "Podsumowanie kosztów VIII Programu Emisji Obligacji",
            "description": "LLM_DESCRIPTION",
            "company": "PCC ROKITA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560616",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 22, 58),
        },
        "https://espiebi.pap.pl/node/667706": {
            "type": "EBI",
            "title": "Rejestracja przez Sąd podwyższenia kapitału zakładowego oraz zmiana Statutu Spółk",
            "description": "Zarząd genXone S.A. ( „Spółka”, „Emitent”) informuje, iż w dniu 22.07.2024 roku powziął informację, iż w dniu 19.07.2024 roku Sąd Rejonowy Poznań - Nowe Miasto i Wilda w Poznaniu, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego dokonał rejestracji i wpisu w Krajowym Rejestrze Sądowym podwyższenia kapitału i zmiany Statutu Spółki.\n                     Podwyższenie kapitału odbyło się na podstawie Uchwały Zarządu z dnia 10 maja 2024 r. w sprawie podwyższenia kapitału zakładowego Spółki w ramach kapitału docelowego w drodze emisji nowych akcji serii F z wyłączeniem prawa poboru dotychczasowych akcjonariuszy oraz zmiany §6 ust.1 Statutu Spółki, o której Spółka informowała raportem bieżącym nr 6/2024 z dnia 10 maja 2024 r..\n                     Kapitał zakładowy Spółki został podwyższony z kwoty 3.296.600 zł do kwoty 3.304.820,00 zł w drodze emisji 8.220 akcji zwykłych na okaziciela serii F o wartości nominalnej 1,00 zł każda. W wyniku rejestracji podwyższenia kapitału zmianie uległ §6 ust. 1 Statutu.\n                     Aktualna wysokość kapitału zakładowego Spółki wynosi 3.304.820 zł. Kapitał dzieli się na 3.304.820 akcji o wartości nominalnej 1,00 zł każda akcja, w tym:\n                     a) 2.039.000 akcji na okaziciela serii A, o numerach od 0000001 do 2039000, o wartości nominalnej 1,00 zł każda,\n                     b) 350.000 akcji na okaziciela serii B, o numerach od 000001 do 350000, o wartości nominalnej 1,00 zł każda,\n                     c) 306.000 akcji na okaziciela serii C, o numerach 000001 do 306000, o wartości nominalnej 1,00 zł każda,\n                     d) 600.000 akcji na okaziciela serii D, o numerach 000001 do 600000, o wartości nominalnej 1,00 zł każda,\n                     e) 1.600 akcji na okaziciela serii E, o numerach 0001 do 1600, o wartości nominalnej 1,00 zł każda,\n                     f) 8.220 akcji na okaziciela serii F, o numerach 0001 do 8220, o wartości nominalnej 1,00 zł każda.\n                     Zakres dokonanej zmiany Statutu Spółki:\n                     Dotychczasowy § 6 ust. 1 Statutu w brzmieniu:\n                     § 6.\n                     Kapitał zakładowy. Akcje. Zbywanie akcji\n                     1. Kapitał zakładowy Spółki wynosi 3.296.600 zł i dzieli się na:\n                     a) 2.039.000 akcji na okaziciela serii A, o numerach od 0000001 do 2039000, o wartości nominalnej 1,00 zł każda,\n                     b) 350.000 akcji na okaziciela serii B, o numerach od 000001 do 350000, o wartości nominalnej 1,00 zł każda,\n                     c) 306.000 akcji na okaziciela serii C, o numerach 000001 do 306000, o wartości nominalnej 1,00 zł każda,\n                     d) 600.000 akcji na okaziciela serii D, o numerach 000001 do 600000, o wartości nominalnej 1,00 zł każda.\n                     e) 1.600 akcji na okaziciela serii E, o numerach 0001 do 1600, o wartości nominalnej 1,00 zł każda. \n                     otrzymuje brzmienie:\n                     § 6.\n                     Kapitał zakładowy. Akcje. Zbywanie akcji\n                     1. Kapitał zakładowy Spółki wynosi 3.304.820 zł i dzieli się na:\n                     a. 2.039.000 akcji na okaziciela serii A, o numerach od 0000001 do 2039000, o wartości nominalnej 1,00 zł każda,\n                     b. 350.000 akcji na okaziciela serii B, o numerach od 000001 do 350000, o wartości nominalnej 1,00 zł każda,\n                     c. 306.000 akcji na okaziciela serii C, o numerach 000001 do 306000, o wartości nominalnej 1,00 zł każda,\n                     d. 600.000 akcji na okaziciela serii D, o numerach 000001 do 600000, o wartości nominalnej 1,00 zł każda,\n                     e. 1.600 akcji na okaziciela serii E, o numerach 0001 do 1600, o wartości nominalnej 1,00 zł każda,\n                     f. 8.220 akcji na okaziciela serii F, o numerach 0001 do 8220 o wartości nominalnej 1,00 zł każda.\n                     Tekst jednolity Statutu Spółki uwzględniający zarejestrowane zmiany Statutu stanowi załącznik do niniejszego raportu.\n                     Podstawa prawna: § 3 ust. 1 pkt 2) oraz § 4 ust. 2 pkt 2b Załącznika nr 3 do Regulaminu Alternatywnego Systemu Obrotu Informacje bieżące i okresowe przekazywane w alternatywnym systemie obrotu na rynku NewConnect .",
            "company": "GENXONE",
            "source": "https://espiebi.pap.pl/node/667706",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 21, 54),
        },
        "https://espiebi.pap.pl/node/560615": {
            "type": "ESPI",
            "title": "Transakcje wykonane w ramach realizacji Programu Odkupu akcji własnych",
            "description": "LLM_DESCRIPTION",
            "company": "AmRest Holdings SE",
            "source": "https://espiebi.pap.pl/node/560615",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 21, 48),
        },
        "https://espiebi.pap.pl/node/560614": {
            "type": "ESPI",
            "title": "Zamknięcie obrad Zwyczajnego Zgromadzenia Akcjonariuszy Spółki z dnia 22 lipca 2024 roku zwołanego na godzinę 16:00 bez podejmowania uchwał",
            "description": "LLM_DESCRIPTION",
            "company": "KORPORACJA GOSPODARCZA EFEKT SA",
            "source": "https://espiebi.pap.pl/node/560614",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 21, 5),
        },
        "https://espiebi.pap.pl/node/667705": {
            "type": "EBI",
            "title": "Życiorysy zawodowe Członków Rady Nadzorczej Emitenta powołanych na nową kadencję.",
            "description": "Zarząd BIOMASS ENERGY PROJECT S.A („Emitent”) („Spółka”) publikuje w załączniku życiorysy Członków Rady Nadzorczej Emitenta powołanych na nową kadencję.\n                     Podstawa prawna:\n                     § 3 ust. 1 pkt 7 Załącznika nr 3 do Regulaminu Alternatywnego Systemu Obrotu “Informacje bieżące i okresowe przekazywane w alternatywnym systemie obrotu na rynku NewConnect”.",
            "company": "BIOMASS",
            "source": "https://espiebi.pap.pl/node/667705",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 52),
        },
        "https://espiebi.pap.pl/node/560613": {
            "type": "ESPI",
            "title": "Doręczenie Spółce odpisu nakazu zapłaty",
            "description": "LLM_DESCRIPTION",
            "company": "REMOR SOLAR SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560613",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 45),
        },
        "https://espiebi.pap.pl/node/560612": {
            "type": "ESPI",
            "title": "Wykup i umorzenie obligacji serii F",
            "description": "LLM_DESCRIPTION",
            "company": "CI GAMES SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560612",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 43),
        },
        "https://espiebi.pap.pl/node/560611": {
            "type": "ESPI",
            "title": "Nabycie udziaów w Spółce hiPower Labs",
            "description": "LLM_DESCRIPTION",
            "company": "Arena.pl SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560611",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 42),
        },
        "https://espiebi.pap.pl/node/560610": {
            "type": "ESPI",
            "title": "Warunkowa autoryzacja Europejskiej Agencji Leków badania klinicznego fazy II w projekcie PreTreg (cukrzyca przedobjawowa typu 1)",
            "description": "LLM_DESCRIPTION",
            "company": "POLTREG SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560610",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 41),
        },
        "https://espiebi.pap.pl/node/560609": {
            "type": "ESPI",
            "title": "Acquisition of a Large Shareholding_JTFG, RMSM, Forest Hill Company",
            "description": "LLM_DESCRIPTION",
            "company": "TATRY MOUNTAIN RESORTS, A.S.",
            "source": "https://espiebi.pap.pl/node/560609",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 40),
        },
        "https://espiebi.pap.pl/node/560608": {
            "type": "ESPI",
            "title": "Zamknięcie lokalu w Browarach Warszawskich_operator K7 Sp. z o.o.",
            "description": "LLM_DESCRIPTION",
            "company": "SAKANA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560608",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 31),
        },
        "https://espiebi.pap.pl/node/560607": {
            "type": "ESPI",
            "title": "Wykaz akcjonariuszy posiadających powyżej 5% głosów na Nadzwyczajnym Walnym Zgromadzeniu",
            "description": "LLM_DESCRIPTION",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560607",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 24),
        },
        "https://espiebi.pap.pl/node/560606": {
            "type": "ESPI",
            "title": "Uchwały podjęte przez Nadzwyczajne Walne Zgromadzenie Spółki",
            "description": "LLM_DESCRIPTION",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560606",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 20, 23),
        },
        "https://espiebi.pap.pl/node/667704": {
            "type": "EBI",
            "title": "Terminy publikacji raportów okresowych w 2024 r.",
            "description": 'Zarząd Green Zebras Spółka Akcyjna z siedzibą we Wrocławiu („Spółka” lub „Emitent”) informuje, że raporty okresowe w roku obrotowym 2024 będą przekazywane w następujących terminach:\n                     • raport kwartalny za II kwartał 2024 roku - 12 sierpnia 2024 roku,\n                     • raport kwartalny za III kwartał 2024 roku - 12 listopada 2024 roku.\n                     Ewentualne zmiany dat przekazywania raportów okresowych będą podane do publicznej wiadomości w formie raportu bieżącego.\n                     Podstawa prawna: §6 ust. 14.1 Załącznika nr 3 do Regulaminu Alternatywnego Systemu Obrotu “Informacje bieżące i okresowe przekazywane w alternatywnym systemie obrotu na rynku NewConnect".',
            "company": "GREEN ZEBRAS",
            "source": "https://espiebi.pap.pl/node/667704",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 22),
        },
        "https://espiebi.pap.pl/node/667703": {
            "type": "EBI",
            "title": "Zakres stosowanych zasad „Dobrych Praktyk Spółek Notowanych na NewConnect 2024”.",
            "description": 'Zarząd Green Zebras Spółka Akcyjna z siedzibą we Wrocławiu („Spółka” lub „Emitent”) przekazuje informację na temat stosowania przez Spółkę zasad ładu korporacyjnego określonego w Załączniku do Uchwały nr 1404/2023 Zarządu Giełdy Papierów Wartościowych w Warszawie S.A. z dnia 18 grudnia 2023 r.\n                     Zestawienie zawierające ustosunkowanie się Emitenta do zasad „Dobrych Praktyk Spółek Notowanych na NewConnect 2024” znajduje się w załączeniu do niniejszego raportu.\n                     Podstawa prawna: § 4 ust. pkt 4 ppkt 4a Załącznika nr 3 do Regulaminu Alternatywnego Systemu Obrotu “Informacje bieżące i okresowe przekazywane w alternatywnym systemie obrotu na rynku NewConnect"',
            "company": "GREEN ZEBRAS",
            "source": "https://espiebi.pap.pl/node/667703",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 15),
        },
        "https://espiebi.pap.pl/node/560605": {
            "type": "ESPI",
            "title": "Zawarcie przez spółkę zależną umowy ramowej dla linii wieloproduktowej z mBank S.A.",
            "description": "LLM_DESCRIPTION",
            "company": "DEKPOL SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560605",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 19, 13),
        },
        "https://espiebi.pap.pl/node/560604": {
            "type": "ESPI",
            "title": "OPERATIONS UPDATE FOR THE THREE MONTHS ENDED 30 JUNE 2024",
            "description": "LLM_DESCRIPTION",
            "company": "KERNEL HOLDING S.A.",
            "source": "https://espiebi.pap.pl/node/560604",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 18, 53),
        },
        "https://espiebi.pap.pl/node/667702": {
            "type": "EBI",
            "title": "Liczba aktywnych kart SIM w Grupie Kapitałowej Telestrada S.A. w czerwcu 2024",
            "description": "Zgodnie ze zobowiązaniem do raportowania informacji o liczbie aktywnych kart SIM w Grupie Kapitałowej Telestrada Zarząd Spółki Telestrada S.A. przekazuje dane za czerwiec 2024 (w sztukach).\n                     Liczba aktywnych kart SIM w GK Telestrada S.A.VI 2024: 94 893.",
            "company": "TELESTRADA",
            "source": "https://espiebi.pap.pl/node/667702",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 17, 43),
        },
        "https://espiebi.pap.pl/node/560603": {
            "type": "ESPI",
            "title": "Nabycie akcji przez osobę zarządzającą",
            "description": "LLM_DESCRIPTION",
            "company": "PKP CARGO SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560603",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 17, 35),
        },
        "https://espiebi.pap.pl/node/560602": {
            "type": "ESPI",
            "title": "ZWCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "IPOPEMA EKOLOGII I INNOWACJI FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560602",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 17, 3),
        },
        "https://espiebi.pap.pl/node/560601": {
            "type": "ESPI",
            "title": "Skup Akcji Własnych",
            "description": "LLM_DESCRIPTION",
            "company": "MONNARI TRADE Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560601",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 16, 59),
        },
        "https://espiebi.pap.pl/node/560600": {
            "type": "ESPI",
            "title": "Zawarcie przyrzeczonych umów sprzedaży akcji Spółki oraz umowy akcjonariuszy",
            "description": "LLM_DESCRIPTION",
            "company": "SESCOM SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560600",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 16, 54),
        },
        "https://espiebi.pap.pl/node/560599": {
            "type": "ESPI",
            "title": "Zmiany w Radzie Nadzorczej Spółki",
            "description": "LLM_DESCRIPTION",
            "company": "POLWAX SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560599",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 16, 7),
        },
        "https://espiebi.pap.pl/node/560598": {
            "type": "ESPI",
            "title": "Zawarcie przez jednostkę zależną Spółki umowy kredytu",
            "description": "LLM_DESCRIPTION",
            "company": "KREDYT INKASO SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560598",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 16, 5),
        },
        "https://espiebi.pap.pl/node/560597": {
            "type": "ESPI",
            "title": "Informacja o transakcjach wykonywanych przez osobę blisko związaną z osobami pełniącymi obowiązki zarządcze",
            "description": "LLM_DESCRIPTION",
            "company": "Dr. Miele Cosmed Group Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560597",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 16, 4),
        },
        "https://espiebi.pap.pl/node/560596": {
            "type": "ESPI",
            "title": "Szacunkowe wyniki za pierwsze półrocze 2024 roku",
            "description": "LLM_DESCRIPTION",
            "company": "NOVITA SA",
            "source": "https://espiebi.pap.pl/node/560596",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 15, 5),
        },
        "https://espiebi.pap.pl/node/560595": {
            "type": "ESPI",
            "title": "Zawarcie istotnej umowy",
            "description": "LLM_DESCRIPTION",
            "company": "ECO5TECH SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560595",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 15, 3),
        },
        "https://espiebi.pap.pl/node/560594": {
            "type": "ESPI",
            "title": "Wstępne wyniki produkcyjne i sprzedażowe Grupy KGHM Polska Miedź S.A. za czerwiec 2024 r.",
            "description": "LLM_DESCRIPTION",
            "company": "KGHM POLSKA MIEDŹ SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560594",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 59),
        },
        "https://espiebi.pap.pl/node/560593": {
            "type": "ESPI",
            "title": "Podjęcie przez Zarząd Spółki uchwały w sprawie przeprowadzenia skupu akcji własnych Spółki w związku z programem motywacyjnym",
            "description": "LLM_DESCRIPTION",
            "company": "LENA LIGHTING SA",
            "source": "https://espiebi.pap.pl/node/560593",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 44),
        },
        "https://espiebi.pap.pl/node/560592": {
            "type": "ESPI",
            "title": "Rozszerzenie współpracy w ramach umowy ramowej z Voodoo",
            "description": "LLM_DESCRIPTION",
            "company": "QUBICGAMES SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560592",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 43),
        },
        "https://espiebi.pap.pl/node/560591": {
            "type": "ESPI",
            "title": "Otrzymanie zawiadomienia w trybie art. 69 ustawy o ofercie publicznej - zwiększenie stanu posiadanego udziału w ogólnej liczbie głosów w Spółce",
            "description": "LLM_DESCRIPTION",
            "company": "G-Devs Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560591",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 35),
        },
        "https://espiebi.pap.pl/node/560590": {
            "type": "ESPI",
            "title": "Rozpoczęcie nabywania akcji własnych w ramach Programu Skupu Akcji Własnych 2024",
            "description": "LLM_DESCRIPTION",
            "company": "BBI DEVELOPMENT SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560590",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 13),
        },
        "https://espiebi.pap.pl/node/560589": {
            "type": "ESPI",
            "title": "Terminy przekazywania raportów okresowych w roku obrotowym 2024/2025",
            "description": "LLM_DESCRIPTION",
            "company": "AMBRA S.A.",
            "source": "https://espiebi.pap.pl/node/560589",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 12),
        },
        "https://espiebi.pap.pl/node/560588": {
            "type": "ESPI",
            "title": "Transakcje na akcjach Emitenta dokonane przez osobę pełniącą obowiązki zarządcze",
            "description": "LLM_DESCRIPTION",
            "company": "G-Devs Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560588",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 11),
        },
        "https://espiebi.pap.pl/node/560587": {
            "type": "ESPI",
            "title": "Zgoda Komisji Nadzoru Finansowego na powołanie Pana Mirosława Czekaja na stanowisko Prezesa Zarządu Banku Gospodarstwa Krajowego.",
            "description": "LLM_DESCRIPTION",
            "company": "BANK GOSPODARSTWA KRAJOWEGO",
            "source": "https://espiebi.pap.pl/node/560587",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 4),
        },
        "https://espiebi.pap.pl/node/560586": {
            "type": "ESPI",
            "title": "Zgoda Komisji Nadzoru Finansowego na powołanie Pana Mirosława Czekaja na stanowisko Prezesa Zarządu Banku Gospodarstwa Krajowego.",
            "description": "LLM_DESCRIPTION",
            "company": "BANK GOSPODARSTWA KRAJOWEGO",
            "source": "https://espiebi.pap.pl/node/560586",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 2),
        },
        "https://espiebi.pap.pl/node/560585": {
            "type": "ESPI",
            "title": "Informacja o transakcjach uzyskana w trybie art. 19 MAR",
            "description": "LLM_DESCRIPTION",
            "company": "KRUK SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560585",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 14, 2),
        },
        "https://espiebi.pap.pl/node/560584": {
            "type": "ESPI",
            "title": "Uchwały Nadzwyczajnego Walnego Zgromadzenia Spółki zwołanego na dzień 25 czerwca 2024 roku podjęte po wznowieniu obrad w dniu 22 lipca 2024 roku",
            "description": "LLM_DESCRIPTION",
            "company": "POLWAX SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560584",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 56),
        },
        "https://espiebi.pap.pl/node/560583": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF TBSP PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560583",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 48),
        },
        "https://espiebi.pap.pl/node/560582": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF OBLIGACJI 6M PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560582",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 43),
        },
        "https://espiebi.pap.pl/node/560581": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF WIG20short PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560581",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 39),
        },
        "https://espiebi.pap.pl/node/560580": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF sWIG80TR PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560580",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 34),
        },
        "https://espiebi.pap.pl/node/560579": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF WIG20lev PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560579",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 30),
        },
        "https://espiebi.pap.pl/node/560578": {
            "type": "ESPI",
            "title": "Podpisanie umowy na zaprojektowanie i budowę drogi ekspresowej S11 na odcinku Kępno - granica województwa opolskiego, odc. II, Siemianice - Gotartów",
            "description": "LLM_DESCRIPTION",
            "company": "MIRBUD SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560578",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 30),
        },
        "https://espiebi.pap.pl/node/560577": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF S_P 500 PLN-HEDGED PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560577",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 26),
        },
        "https://espiebi.pap.pl/node/560576": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF NASDAQ-100 PLN-HEDGED PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560576",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 21),
        },
        "https://espiebi.pap.pl/node/560575": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF mWIG40TR PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560575",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 17),
        },
        "https://espiebi.pap.pl/node/560574": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF WIG20TR PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560574",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 12),
        },
        "https://espiebi.pap.pl/node/560573": {
            "type": "ESPI",
            "title": "Zgoda Rady Nadzorczej JSW S.A. na umorzenie Certyfikatów Inwestycyjnych JSW Stabilizacyjnego Funduszu Inwestycyjnego Zamkniętego w ramach ustalonego na 2024 rok limitu",
            "description": "LLM_DESCRIPTION",
            "company": "JASTRZĘBSKA SPÓŁKA WĘGLOWA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560573",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 11),
        },
        "https://espiebi.pap.pl/node/560572": {
            "type": "ESPI",
            "title": "Sales revenues for June 2024",
            "description": "LLM_DESCRIPTION",
            "company": "SOPHARMA AD",
            "source": "https://espiebi.pap.pl/node/560572",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 6),
        },
        "https://espiebi.pap.pl/node/560571": {
            "type": "ESPI",
            "title": "Sprostowanie tytułu raportu nr 9/2024 z dnia 19 lipca 2024 roku",
            "description": "LLM_DESCRIPTION",
            "company": "EUROSNACK SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560571",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 12, 43),
        },
        "https://espiebi.pap.pl/node/560570": {
            "type": "ESPI",
            "title": "Rezygnacja członka Rady Nadzorczej Unibep S.A.",
            "description": "LLM_DESCRIPTION",
            "company": "UNIBEP SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560570",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 12, 41),
        },
        "https://espiebi.pap.pl/node/560569": {
            "type": "ESPI",
            "title": "Transakcja zrealizowana przez osobę pełniącą obowiązki zarządcze",
            "description": "LLM_DESCRIPTION",
            "company": "PRYMUS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560569",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 12, 3),
        },
        "https://espiebi.pap.pl/node/560568": {
            "type": "ESPI",
            "title": "Nabycie akcji własnych",
            "description": "LLM_DESCRIPTION",
            "company": "MERCOR SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560568",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 11, 33),
        },
        "https://espiebi.pap.pl/node/560567": {
            "type": "ESPI",
            "title": "Opinia Zarządu w przedmiocie uzasadnienia wyłączenia prawa poboru akcji serii J oraz sposobu ustalenia ceny emisyjnej akcji serii J",
            "description": "LLM_DESCRIPTION",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560567",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 11, 30),
        },
        "https://espiebi.pap.pl/node/560566": {
            "type": "ESPI",
            "title": "Żądanie akcjonariusza umieszczania określonych spraw w porządku obrad walnego zgromadzenia",
            "description": "LLM_DESCRIPTION",
            "company": "NOVINA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560566",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 11, 13),
        },
        "https://espiebi.pap.pl/node/560565": {
            "type": "ESPI",
            "title": "Opinia Zarządu w przedmiocie uzasadnienia wyłączenia prawa poboru akcji serii J oraz sposobu ustalenia ceny emisyjnej akcji serii J",
            "description": "LLM_DESCRIPTION",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560565",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 11, 5),
        },
        "https://espiebi.pap.pl/node/560564": {
            "type": "ESPI",
            "title": "Zgłoszenie kandydata na członka Rady Nadzorczej",
            "description": "LLM_DESCRIPTION",
            "company": "BENEFIT SYSTEMS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560564",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 10, 16),
        },
        "https://espiebi.pap.pl/node/560563": {
            "type": "ESPI",
            "title": "Odmowa rejestracji umowy o utworzeniu Podatkowej Grupy Kapitałowej - podtrzymanie decyzji",
            "description": "LLM_DESCRIPTION",
            "company": "KOMPUTRONIK SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560563",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 10, 4),
        },
        "https://espiebi.pap.pl/node/560562": {
            "type": "ESPI",
            "title": "RB_FI_E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "EQUES AKUMULACJI MAJĄTKU FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560562",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 9, 50),
        },
        "https://espiebi.pap.pl/node/560561": {
            "type": "ESPI",
            "title": "RB_FI_E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "EQUES AKTYWNEGO INWESTOWANIA FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560561",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 9, 43),
        },
        "https://espiebi.pap.pl/node/560560": {
            "type": "ESPI",
            "title": "Informacja o szacunkowych miesięcznych skonsolidowanych przychodach za czerwiec 2024 r.",
            "description": "LLM_DESCRIPTION",
            "company": "ASBISc ENTERPRISES PLC",
            "source": "https://espiebi.pap.pl/node/560560",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 8, 41),
        },
        "https://espiebi.pap.pl/node/560559": {
            "type": "ESPI",
            "title": 'Wykaz akcjonariuszy posiadających co najmniej 5% głosów na Zwyczajnym Walnym Zgromadzeniu Akcjonariuszy spółki Giełda Praw Majątkowych "Vindexus" S. A. w Warszawie zwołanym na dzień 21 czerwca 2024 roku, które po dwóch przerwach...',
            "description": "LLM_DESCRIPTION",
            "company": "GIEŁDA PRAW MAJĄTKOWYCH VINDEXUS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560559",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 7, 33),
        },
        "https://espiebi.pap.pl/node/560558": {
            "type": "ESPI",
            "title": "Uchwały podjęte przez Zwyczajne Walne Zgromadzenie w dniu 19 lipca 2024 r.",
            "description": "LLM_DESCRIPTION",
            "company": "GIEŁDA PRAW MAJĄTKOWYCH VINDEXUS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560558",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 7, 20),
        },
    }

    scraper = EspiEbiPapScraper()

    dt = datetime(year=2024, month=7, day=22)
    async with LLMClientManaged(
        "http://localhost", "", "", manager=ModelManager(["model_1"])
    ) as client_1:
        with mock.patch.object(client_1, "get_espi_summary") as mock_fn:
            mock_fn.return_value = (
                EspiLLMSummary(title="LLM_TITLE", description="LLM_DESCRIPTION"),
                "model_1",
            )

            items = await scraper.scrape(pap_test_client, dt, dt, [], [client_1])
            items_dict = {
                item.source: {
                    "type": item.type,
                    "title": item.title,
                    "description": item.description,
                    "company": item.company,
                    "source": item.source,
                    "parsed_by_llm": item.parsed_by_llm,
                    "date": item.date,
                }
                for item in items
            }
            assert items_dict == expected
