from datetime import datetime
from unittest import mock

from gpw_scraper.llm import LLMClientManaged, ModelManager
from gpw_scraper.schemas.espi_ebi import EspiLLMSummary
from gpw_scraper.scrapers.pap import EspiEbiPapScraper


async def test_espi_ebi_pap_scraper_scrape(pap_test_client):
    expected = {
        "https://espiebi.pap.pl/node/560617": {
            "type": "ESPI",
            "title": "Podsumowanie kosztów VI Programu Emisji Obligacji",
            "description": "\n\nZarząd PCC EXOL SA z si",
            "company": "PCC EXOL SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560617",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 23, 9),
        },
        "https://espiebi.pap.pl/node/560616": {
            "type": "ESPI",
            "title": "Podsumowanie kosztów VIII Programu Emisji Obligacji",
            "description": "\n\nZarząd PCC Rokita SA z ",
            "company": "PCC ROKITA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560616",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 22, 58),
        },
        "https://espiebi.pap.pl/node/667706": {
            "type": "EBI",
            "title": "Rejestracja przez Sąd podwyższenia kapitału zakładowego oraz zmiana Statutu Spółk",
            "description": "Zarząd genXone S.A. ( „Sp",
            "company": "GENXONE",
            "source": "https://espiebi.pap.pl/node/667706",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 21, 54),
        },
        "https://espiebi.pap.pl/node/560615": {
            "type": "ESPI",
            "title": "Transakcje wykonane w ramach realizacji Programu Odkupu akcji własnych",
            "description": '\n\nAmRest Holdings SE ("Am',
            "company": "AmRest Holdings SE",
            "source": "https://espiebi.pap.pl/node/560615",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 21, 48),
        },
        "https://espiebi.pap.pl/node/560614": {
            "type": "ESPI",
            "title": "Zamknięcie obrad Zwyczajnego Zgromadzenia Akcjonariuszy Spółki z dnia 22 lipca 2024 roku zwołanego na godzinę 16:00 bez podejmowania uchwał",
            "description": "\n\nZarząd Korporacji Gospo",
            "company": "KORPORACJA GOSPODARCZA EFEKT SA",
            "source": "https://espiebi.pap.pl/node/560614",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 21, 5),
        },
        "https://espiebi.pap.pl/node/667705": {
            "type": "EBI",
            "title": "Życiorysy zawodowe Członków Rady Nadzorczej Emitenta powołanych na nową kadencję.",
            "description": "Zarząd BIOMASS ENERGY PRO",
            "company": "BIOMASS",
            "source": "https://espiebi.pap.pl/node/667705",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 52),
        },
        "https://espiebi.pap.pl/node/560613": {
            "type": "ESPI",
            "title": "Doręczenie Spółce odpisu nakazu zapłaty",
            "description": "\n\nZarząd REMOR SOLAR POLS",
            "company": "REMOR SOLAR SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560613",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 45),
        },
        "https://espiebi.pap.pl/node/560612": {
            "type": "ESPI",
            "title": "Wykup i umorzenie obligacji serii F",
            "description": "\n\nZarząd CI Games SE z si",
            "company": "CI GAMES SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560612",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 43),
        },
        "https://espiebi.pap.pl/node/560611": {
            "type": "ESPI",
            "title": "Nabycie udziaów w Spółce hiPower Labs",
            "description": "\n\nZarząd hiPower Energy S",
            "company": "Arena.pl SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560611",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 42),
        },
        "https://espiebi.pap.pl/node/560610": {
            "type": "ESPI",
            "title": "Warunkowa autoryzacja Europejskiej Agencji Leków badania klinicznego fazy II w projekcie PreTreg (cukrzyca przedobjawowa typu 1)",
            "description": "\n\nZarząd spółki PolTREG S",
            "company": "POLTREG SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560610",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 41),
        },
        "https://espiebi.pap.pl/node/560609": {
            "type": "ESPI",
            "title": "Acquisition of a Large Shareholding_JTFG, RMSM, Forest Hill Company",
            "description": "\n\nAcquisition of a Large ",
            "company": "TATRY MOUNTAIN RESORTS, A.S.",
            "source": "https://espiebi.pap.pl/node/560609",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 40),
        },
        "https://espiebi.pap.pl/node/560608": {
            "type": "ESPI",
            "title": "Zamknięcie lokalu w Browarach Warszawskich_operator K7 Sp. z o.o.",
            "description": "\n\nZarząd Spółki SAKANA S.",
            "company": "SAKANA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560608",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 31),
        },
        "https://espiebi.pap.pl/node/560607": {
            "type": "ESPI",
            "title": "Wykaz akcjonariuszy posiadających powyżej 5% głosów na Nadzwyczajnym Walnym Zgromadzeniu",
            "description": "\n\nZarząd spółki ManyDev S",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560607",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 24),
        },
        "https://espiebi.pap.pl/node/560606": {
            "type": "ESPI",
            "title": "Uchwały podjęte przez Nadzwyczajne Walne Zgromadzenie Spółki",
            "description": "\n\nZarząd spółki ManyDev S",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560606",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 23),
        },
        "https://espiebi.pap.pl/node/667704": {
            "type": "EBI",
            "title": "Terminy publikacji raportów okresowych w 2024 r.",
            "description": "Zarząd Green Zebras Spółk",
            "company": "GREEN ZEBRAS",
            "source": "https://espiebi.pap.pl/node/667704",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 22),
        },
        "https://espiebi.pap.pl/node/667703": {
            "type": "EBI",
            "title": "Zakres stosowanych zasad „Dobrych Praktyk Spółek Notowanych na NewConnect 2024”.",
            "description": "Zarząd Green Zebras Spółk",
            "company": "GREEN ZEBRAS",
            "source": "https://espiebi.pap.pl/node/667703",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 20, 15),
        },
        "https://espiebi.pap.pl/node/560605": {
            "type": "ESPI",
            "title": "Zawarcie przez spółkę zależną umowy ramowej dla linii wieloproduktowej z mBank S.A.",
            "description": '\n\nZarząd Dekpol S.A. ("Em',
            "company": "DEKPOL SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560605",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 19, 13),
        },
        "https://espiebi.pap.pl/node/560604": {
            "type": "ESPI",
            "title": "OPERATIONS UPDATE FOR THE THREE MONTHS ENDED 30 JUNE 2024",
            "description": "\n\nKernel Holding S.A. inf",
            "company": "KERNEL HOLDING S.A.",
            "source": "https://espiebi.pap.pl/node/560604",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 18, 53),
        },
        "https://espiebi.pap.pl/node/667702": {
            "type": "EBI",
            "title": "Liczba aktywnych kart SIM w Grupie Kapitałowej Telestrada S.A. w czerwcu 2024",
            "description": "Zgodnie ze zobowiązaniem ",
            "company": "TELESTRADA",
            "source": "https://espiebi.pap.pl/node/667702",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 17, 43),
        },
        "https://espiebi.pap.pl/node/560603": {
            "type": "ESPI",
            "title": "Nabycie akcji przez osobę zarządzającą",
            "description": "\n\nZarząd PKP CARGO S.A. (",
            "company": "PKP CARGO SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560603",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 17, 35),
        },
        "https://espiebi.pap.pl/node/560602": {
            "type": "ESPI",
            "title": "ZWCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "IPOPEMA EKOLOGII I INNOWACJI FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560602",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 17, 3),
        },
        "https://espiebi.pap.pl/node/560601": {
            "type": "ESPI",
            "title": "Skup Akcji Własnych",
            "description": "\n\nZarząd MONNARI TRADE S.",
            "company": "MONNARI TRADE Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560601",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 16, 59),
        },
        "https://espiebi.pap.pl/node/560600": {
            "type": "ESPI",
            "title": "Zawarcie przyrzeczonych umów sprzedaży akcji Spółki oraz umowy akcjonariuszy",
            "description": '\n\nZarząd Sescom S.A. ("Sp',
            "company": "SESCOM SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560600",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 16, 54),
        },
        "https://espiebi.pap.pl/node/560599": {
            "type": "ESPI",
            "title": "Zmiany w Radzie Nadzorczej Spółki",
            "description": "\n\nZarząd Spółki Polwax S.",
            "company": "POLWAX SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560599",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 16, 7),
        },
        "https://espiebi.pap.pl/node/560598": {
            "type": "ESPI",
            "title": "Zawarcie przez jednostkę zależną Spółki umowy kredytu",
            "description": "\n\nZarząd Kredyt Inkaso S.",
            "company": "KREDYT INKASO SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560598",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 16, 5),
        },
        "https://espiebi.pap.pl/node/560597": {
            "type": "ESPI",
            "title": "Informacja o transakcjach wykonywanych przez osobę blisko związaną z osobami pełniącymi obowiązki zarządcze",
            "description": "\n\nDr. Miele Cosmed Group ",
            "company": "Dr. Miele Cosmed Group Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560597",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 16, 4),
        },
        "https://espiebi.pap.pl/node/560596": {
            "type": "ESPI",
            "title": "Szacunkowe wyniki za pierwsze półrocze 2024 roku",
            "description": "\n\nZarząd NOVITA S.A. z si",
            "company": "NOVITA SA",
            "source": "https://espiebi.pap.pl/node/560596",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 15, 5),
        },
        "https://espiebi.pap.pl/node/560595": {
            "type": "ESPI",
            "title": "Zawarcie istotnej umowy",
            "description": "\n\nW nawiązaniu do Raportu",
            "company": "ECO5TECH SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560595",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 15, 3),
        },
        "https://espiebi.pap.pl/node/560594": {
            "type": "ESPI",
            "title": "Wstępne wyniki produkcyjne i sprzedażowe Grupy KGHM Polska Miedź S.A. za czerwiec 2024 r.",
            "description": "\n\nZarząd KGHM Polska Mied",
            "company": "KGHM POLSKA MIEDŹ SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560594",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 59),
        },
        "https://espiebi.pap.pl/node/560593": {
            "type": "ESPI",
            "title": "Podjęcie przez Zarząd Spółki uchwały w sprawie przeprowadzenia skupu akcji własnych Spółki w związku z programem motywacyjnym",
            "description": "\n\nZarząd Lena Lighting S.",
            "company": "LENA LIGHTING SA",
            "source": "https://espiebi.pap.pl/node/560593",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 44),
        },
        "https://espiebi.pap.pl/node/560592": {
            "type": "ESPI",
            "title": "Rozszerzenie współpracy w ramach umowy ramowej z Voodoo",
            "description": "\n\nW nawiązaniu do raportu",
            "company": "QUBICGAMES SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560592",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 43),
        },
        "https://espiebi.pap.pl/node/560591": {
            "type": "ESPI",
            "title": "Otrzymanie zawiadomienia w trybie art. 69 ustawy o ofercie publicznej - zwiększenie stanu posiadanego udziału w ogólnej liczbie głosów w Spółce",
            "description": '\n\nZarząd G-DEVS S.A. "Spó',
            "company": "G-Devs Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560591",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 35),
        },
        "https://espiebi.pap.pl/node/560590": {
            "type": "ESPI",
            "title": "Rozpoczęcie nabywania akcji własnych w ramach Programu Skupu Akcji Własnych 2024",
            "description": "\n\nW nawiązaniu do raportu",
            "company": "BBI DEVELOPMENT SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560590",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 13),
        },
        "https://espiebi.pap.pl/node/560589": {
            "type": "ESPI",
            "title": "Terminy przekazywania raportów okresowych w roku obrotowym 2024/2025",
            "description": "\n\nZgodnie z § 80 ust. 1 r",
            "company": "AMBRA S.A.",
            "source": "https://espiebi.pap.pl/node/560589",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 12),
        },
        "https://espiebi.pap.pl/node/560588": {
            "type": "ESPI",
            "title": "Transakcje na akcjach Emitenta dokonane przez osobę pełniącą obowiązki zarządcze",
            "description": '\n\nZarząd G-DEVS S.A. "Emi',
            "company": "G-Devs Spółka Akcyjna",
            "source": "https://espiebi.pap.pl/node/560588",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 11),
        },
        "https://espiebi.pap.pl/node/560587": {
            "type": "ESPI",
            "title": "Zgoda Komisji Nadzoru Finansowego na powołanie Pana Mirosława Czekaja na stanowisko Prezesa Zarządu Banku Gospodarstwa Krajowego.",
            "description": "\n\nPodstawa prawna:§ 5 pkt",
            "company": "BANK GOSPODARSTWA KRAJOWEGO",
            "source": "https://espiebi.pap.pl/node/560587",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 4),
        },
        "https://espiebi.pap.pl/node/560586": {
            "type": "ESPI",
            "title": "Zgoda Komisji Nadzoru Finansowego na powołanie Pana Mirosława Czekaja na stanowisko Prezesa Zarządu Banku Gospodarstwa Krajowego.",
            "description": "\n\nPodstawa prawna:§ 5 pkt",
            "company": "BANK GOSPODARSTWA KRAJOWEGO",
            "source": "https://espiebi.pap.pl/node/560586",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 2),
        },
        "https://espiebi.pap.pl/node/560585": {
            "type": "ESPI",
            "title": "Informacja o transakcjach uzyskana w trybie art. 19 MAR",
            "description": "\n\nKRUK S.A. (Emitent) inf",
            "company": "KRUK SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560585",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 14, 2),
        },
        "https://espiebi.pap.pl/node/560584": {
            "type": "ESPI",
            "title": "Uchwały Nadzwyczajnego Walnego Zgromadzenia Spółki zwołanego na dzień 25 czerwca 2024 roku podjęte po wznowieniu obrad w dniu 22 lipca 2024 roku",
            "description": "\n\nZarząd Spółki Polwax S.",
            "company": "POLWAX SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560584",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 13, 56),
        },
        "https://espiebi.pap.pl/node/560583": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF TBSP PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560583",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 48),
        },
        "https://espiebi.pap.pl/node/560582": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF OBLIGACJI 6M PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560582",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 43),
        },
        "https://espiebi.pap.pl/node/560581": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF WIG20short PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560581",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 39),
        },
        "https://espiebi.pap.pl/node/560580": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF sWIG80TR PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560580",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 34),
        },
        "https://espiebi.pap.pl/node/560579": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF WIG20lev PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560579",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 30),
        },
        "https://espiebi.pap.pl/node/560578": {
            "type": "ESPI",
            "title": "Podpisanie umowy na zaprojektowanie i budowę drogi ekspresowej S11 na odcinku Kępno - granica województwa opolskiego, odc. II, Siemianice - Gotartów",
            "description": "\n\nZarząd MIRBUD S.A. (dal",
            "company": "MIRBUD SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560578",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 13, 30),
        },
        "https://espiebi.pap.pl/node/560577": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF S_P 500 PLN-HEDGED PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560577",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 26),
        },
        "https://espiebi.pap.pl/node/560576": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF NASDAQ-100 PLN-HEDGED PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560576",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 21),
        },
        "https://espiebi.pap.pl/node/560575": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF mWIG40TR PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560575",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 17),
        },
        "https://espiebi.pap.pl/node/560574": {
            "type": "ESPI",
            "title": "WANCI-E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "BETA ETF WIG20TR PORTFELOWY FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560574",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 13, 12),
        },
        "https://espiebi.pap.pl/node/560573": {
            "type": "ESPI",
            "title": "Zgoda Rady Nadzorczej JSW S.A. na umorzenie Certyfikatów Inwestycyjnych JSW Stabilizacyjnego Funduszu Inwestycyjnego Zamkniętego w ramach ustalonego na 2024 rok limitu",
            "description": "\n\nZarząd Jastrzębskiej Sp",
            "company": "JASTRZĘBSKA SPÓŁKA WĘGLOWA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560573",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 13, 11),
        },
        "https://espiebi.pap.pl/node/560572": {
            "type": "ESPI",
            "title": "Sales revenues for June 2024",
            "description": '\n\n"Sopharma" AD (the Comp',
            "company": "SOPHARMA AD",
            "source": "https://espiebi.pap.pl/node/560572",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 13, 6),
        },
        "https://espiebi.pap.pl/node/560571": {
            "type": "ESPI",
            "title": "Sprostowanie tytułu raportu nr 9/2024 z dnia 19 lipca 2024 roku",
            "description": "\n\nZarząd spółki Eurosnack",
            "company": "EUROSNACK SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560571",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 12, 43),
        },
        "https://espiebi.pap.pl/node/560570": {
            "type": "ESPI",
            "title": "Rezygnacja członka Rady Nadzorczej Unibep S.A.",
            "description": "\n\nZarząd Unibep S.A. [Emi",
            "company": "UNIBEP SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560570",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 12, 41),
        },
        "https://espiebi.pap.pl/node/560569": {
            "type": "ESPI",
            "title": "Transakcja zrealizowana przez osobę pełniącą obowiązki zarządcze",
            "description": "\n\nZarząd Prymus S.A. z si",
            "company": "PRYMUS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560569",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 12, 3),
        },
        "https://espiebi.pap.pl/node/560568": {
            "type": "ESPI",
            "title": "Nabycie akcji własnych",
            "description": '\n\nZarząd "MERCOR" S.A. ("',
            "company": "MERCOR SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560568",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 11, 33),
        },
        "https://espiebi.pap.pl/node/560567": {
            "type": "ESPI",
            "title": "Opinia Zarządu w przedmiocie uzasadnienia wyłączenia prawa poboru akcji serii J oraz sposobu ustalenia ceny emisyjnej akcji serii J",
            "description": "\n\nKorekta raportu wynika ",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560567",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 11, 30),
        },
        "https://espiebi.pap.pl/node/560566": {
            "type": "ESPI",
            "title": "Żądanie akcjonariusza umieszczania określonych spraw w porządku obrad walnego zgromadzenia",
            "description": "\n\nZarząd Novina S.A. z si",
            "company": "NOVINA SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560566",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 11, 13),
        },
        "https://espiebi.pap.pl/node/560565": {
            "type": "ESPI",
            "title": "Opinia Zarządu w przedmiocie uzasadnienia wyłączenia prawa poboru akcji serii J oraz sposobu ustalenia ceny emisyjnej akcji serii J",
            "description": "\n\nZarząd Manydev studio S",
            "company": "ManyDev Studio SPÓŁKA EUROPEJSKA",
            "source": "https://espiebi.pap.pl/node/560565",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 11, 5),
        },
        "https://espiebi.pap.pl/node/560564": {
            "type": "ESPI",
            "title": "Zgłoszenie kandydata na członka Rady Nadzorczej",
            "description": "\n\nZarząd Benefit Systems ",
            "company": "BENEFIT SYSTEMS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560564",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 10, 16),
        },
        "https://espiebi.pap.pl/node/560563": {
            "type": "ESPI",
            "title": "Odmowa rejestracji umowy o utworzeniu Podatkowej Grupy Kapitałowej - podtrzymanie decyzji",
            "description": "\n\nZarząd Komputronik S.A.",
            "company": "KOMPUTRONIK SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560563",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 10, 4),
        },
        "https://espiebi.pap.pl/node/560562": {
            "type": "ESPI",
            "title": "RB_FI_E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "EQUES AKUMULACJI MAJĄTKU FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560562",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 9, 50),
        },
        "https://espiebi.pap.pl/node/560561": {
            "type": "ESPI",
            "title": "RB_FI_E_30.04.18",
            "description": "LLM_DESCRIPTION",
            "company": "EQUES AKTYWNEGO INWESTOWANIA FUNDUSZ INWESTYCYJNY ZAMKNIĘTY",
            "source": "https://espiebi.pap.pl/node/560561",
            "parsed_by_llm": "model_1",
            "date": datetime(2024, 7, 22, 9, 43),
        },
        "https://espiebi.pap.pl/node/560560": {
            "type": "ESPI",
            "title": "Informacja o szacunkowych miesięcznych skonsolidowanych przychodach za czerwiec 2024 r.",
            "description": "\n\nRada Dyrektorów ASBISc ",
            "company": "ASBISc ENTERPRISES PLC",
            "source": "https://espiebi.pap.pl/node/560560",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 8, 41),
        },
        "https://espiebi.pap.pl/node/560559": {
            "type": "ESPI",
            "title": 'Wykaz akcjonariuszy posiadających co najmniej 5% głosów na Zwyczajnym Walnym Zgromadzeniu Akcjonariuszy spółki Giełda Praw Majątkowych "Vindexus" S. A. w Warszawie zwołanym na dzień 21 czerwca 2024 roku, które po dwóch przerwach...',
            "description": "\n\nZarząd Spółki Giełda Pr",
            "company": "GIEŁDA PRAW MAJĄTKOWYCH VINDEXUS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560559",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 7, 33),
        },
        "https://espiebi.pap.pl/node/560558": {
            "type": "ESPI",
            "title": "Uchwały podjęte przez Zwyczajne Walne Zgromadzenie w dniu 19 lipca 2024 r.",
            "description": "\n\nZarząd Giełdy Praw Mają",
            "company": "GIEŁDA PRAW MAJĄTKOWYCH VINDEXUS SPÓŁKA AKCYJNA",
            "source": "https://espiebi.pap.pl/node/560558",
            "parsed_by_llm": None,
            "date": datetime(2024, 7, 22, 7, 20),
        },
    }

    scraper = EspiEbiPapScraper()

    dt = datetime(year=2024, month=7, day=22)
    async with LLMClientManaged(
        "http://localhost", "", "", manager=ModelManager(["model_1"])
    ) as client_1:
        with mock.patch.object(client_1, "get_espi_summary") as mock_fn:
            mock_fn.return_value = (
                EspiLLMSummary(title="LLM_TITLE", description="LLM_DESCRIPTION"),
                "model_1",
            )

            items = await scraper.scrape(pap_test_client, dt, dt, [], [client_1])
            items_dict = {
                item.source: {
                    "type": item.type,
                    "title": item.title,
                    "description": item.description[:25]  # :25 to make expected shorter
                    if isinstance(item.description, str)
                    else item.description,
                    "company": item.company,
                    "source": item.source,
                    "parsed_by_llm": item.parsed_by_llm,
                    "date": item.date,
                }
                for item in items
            }
            assert items_dict == expected
