"""Add espi ebi model

Revision ID: 4de9c1afb476
Revises:
Create Date: 2024-09-18 20:34:31.940584

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4de9c1afb476"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    enum = ENUM("ESPI", "EBI", name="entrytype")
    enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "espi_ebi",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("parsed_by_llm", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("espi_ebi_pkey")),
        sa.UniqueConstraint("source", name=op.f("espi_ebi_source_key")),
    )
    # ### end Alembic commands ###
    op.add_column(
        "espi_ebi", sa.Column("type", sa.Enum(name="entrytype"), nullable=False)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("espi_ebi")
    # ### end Alembic commands ###

    sa.Enum(name="entrytype").drop(op.get_bind(), checkfirst=False)
