"""Add tickers metadata

Revision ID: 360bc4174834
Revises: 18da65403b2d
Create Date: 2024-12-18 19:17:02.239067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "360bc4174834"
down_revision: Union[str, None] = "18da65403b2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("currency_symbol", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("industry", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("tickers_metadata_pkey")),
    )
    op.create_index(
        op.f("ix_tickers_metadata_created_at"),
        "tickers_metadata",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickers_metadata_currency_symbol"),
        "tickers_metadata",
        ["currency_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickers_metadata_industry"),
        "tickers_metadata",
        ["industry"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickers_metadata_sector"), "tickers_metadata", ["sector"], unique=False
    )
    op.create_index(
        op.f("ix_tickers_metadata_ticker"), "tickers_metadata", ["ticker"], unique=True
    )
    op.create_index(
        op.f("ix_tickers_metadata_updated_at"),
        "tickers_metadata",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickers_metadata_updated_at"), table_name="tickers_metadata")
    op.drop_index(op.f("ix_tickers_metadata_ticker"), table_name="tickers_metadata")
    op.drop_index(op.f("ix_tickers_metadata_sector"), table_name="tickers_metadata")
    op.drop_index(op.f("ix_tickers_metadata_industry"), table_name="tickers_metadata")
    op.drop_index(
        op.f("ix_tickers_metadata_currency_symbol"), table_name="tickers_metadata"
    )
    op.drop_index(op.f("ix_tickers_metadata_created_at"), table_name="tickers_metadata")
    op.drop_table("tickers_metadata")
    # ### end Alembic commands ###
