"""Add webhooks models

Revision ID: 50d049a95ae1
Revises: 14ce2b33f7e3
Create Date: 2024-10-11 20:50:57.657544

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50d049a95ae1"
down_revision: Union[str, None] = "14ce2b33f7e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    enum_webhook_event_type = ENUM(
        "delivery_fail",
        "delivery_fail_response",
        "delivery_success",
        name="webhookeventtype",
    )
    enum_webhook_event_type.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("webhook_users_pkey")),
        sa.UniqueConstraint("name", name=op.f("webhook_users_name_key")),
    )
    op.create_index(
        op.f("ix_webhook_users_created_at"),
        "webhook_users",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_webhook_users_id"), "webhook_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_webhook_users_updated_at"),
        "webhook_users",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("secret", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["webhook_users.id"],
            name=op.f("webhook_endpoints_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("webhook_endpoints_pkey")),
    )
    op.create_index(
        op.f("ix_webhook_endpoints_created_at"),
        "webhook_endpoints",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_endpoints_id"), "webhook_endpoints", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_endpoints_updated_at"),
        "webhook_endpoints",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_endpoints_user_id"),
        "webhook_endpoints",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("espi_ebi_id", sa.Integer(), nullable=False),
        sa.Column("http_code", sa.Integer(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["espi_ebi_id"],
            ["espi_ebi.id"],
            name=op.f("webhook_events_espi_ebi_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhook_endpoints.id"],
            name=op.f("webhook_events_webhook_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("webhook_events_pkey")),
    )
    op.create_index(
        op.f("ix_webhook_events_created_at"),
        "webhook_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_id"), "webhook_events", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_updated_at"),
        "webhook_events",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("webhook_events_espi_ebi_id_fkey"),
        "webhook_events",
        ["espi_ebi_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_webhook_id"),
        "webhook_events",
        ["webhook_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.add_column(
        "webhook_events",
        sa.Column("type", sa.Enum(name="webhookeventtype"), nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("webhook_events_espi_ebi_id_fkey"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_webhook_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_updated_at"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_created_at"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_webhook_endpoints_user_id"), table_name="webhook_endpoints")
    op.drop_index(
        op.f("ix_webhook_endpoints_updated_at"), table_name="webhook_endpoints"
    )
    op.drop_index(op.f("ix_webhook_endpoints_id"), table_name="webhook_endpoints")
    op.drop_index(
        op.f("ix_webhook_endpoints_created_at"), table_name="webhook_endpoints"
    )
    op.drop_table("webhook_endpoints")
    op.drop_index(op.f("ix_webhook_users_updated_at"), table_name="webhook_users")
    op.drop_index(op.f("ix_webhook_users_id"), table_name="webhook_users")
    op.drop_index(op.f("ix_webhook_users_created_at"), table_name="webhook_users")
    op.drop_table("webhook_users")
    # ### end Alembic commands ###

    sa.Enum(name="webhookeventtype").drop(op.get_bind(), checkfirst=False)
