"""Add stocks ohlc

Revision ID: 2aafce1f7ce5
Revises: 50d049a95ae1
Create Date: 2024-12-17 11:30:08.238626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2aafce1f7ce5"
down_revision: Union[str, None] = "50d049a95ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    enum_source = ENUM(
        "YAHOO_FINANCE",
        name="ohlcdatasource",
    )
    enum_source.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks_ohlc",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("stocks_ohlc_pkey")),
    )
    op.create_index(op.f("ix_stocks_ohlc_date"), "stocks_ohlc", ["date"], unique=False)
    op.create_index(
        op.f("ix_stocks_ohlc_ticker"), "stocks_ohlc", ["ticker"], unique=False
    )
    # ### end Alembic commands ###

    op.add_column(
        "stocks_ohlc",
        sa.Column("source", sa.Enum(name="ohlcdatasource"), nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_ohlc_ticker"), table_name="stocks_ohlc")
    op.drop_index(op.f("ix_stocks_ohlc_date"), table_name="stocks_ohlc")
    op.drop_table("stocks_ohlc")
    # ### end Alembic commands ###

    sa.Enum(name="ohlcdatasource").drop(op.get_bind(), checkfirst=False)
