"""Add currency exchange

Revision ID: 18da65403b2d
Revises: 2aafce1f7ce5
Create Date: 2024-12-18 10:40:43.750158

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18da65403b2d"
down_revision: Union[str, None] = "2aafce1f7ce5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_exchange",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("currency_exchange_pkey")),
    )
    op.create_index(
        op.f("ix_currency_exchange_created_at"),
        "currency_exchange",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_currency_exchange_created_at"), table_name="currency_exchange"
    )
    op.drop_table("currency_exchange")
    # ### end Alembic commands ###
