"""Add fts

Revision ID: b169dc90e86a
Revises: 50d049a95ae1
Create Date: 2025-09-06 13:01:06.629011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b169dc90e86a"
down_revision: str | None = "50d049a95ae1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    ######################################################################
    # REQUIRED: https://github.com/bartosz121/postgres-polish-dictionary #
    ######################################################################

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "espi_ebi",
        sa.Column(
            "_tsvector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "\nsetweight(to_tsvector('pl_ispell', title), 'A') ||\nsetweight(to_tsvector('pl_ispell', description), 'B') ||\nsetweight(to_tsvector('pl_ispell', company), 'D')\n",  # noqa: E501
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_espi_ebi_tsvector", "espi_ebi", ["_tsvector"], unique=False, postgresql_using="gin")
    op.drop_index(op.f("webhook_events_espi_ebi_id_fkey"), table_name="webhook_events")
    op.create_index(op.f("ix_webhook_events_espi_ebi_id"), "webhook_events", ["espi_ebi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_events_espi_ebi_id"), table_name="webhook_events")
    op.create_index(op.f("webhook_events_espi_ebi_id_fkey"), "webhook_events", ["espi_ebi_id"], unique=False)
    op.drop_index("ix_espi_ebi_tsvector", table_name="espi_ebi", postgresql_using="gin")
    op.drop_column("espi_ebi", "_tsvector")
    # ### end Alembic commands ###
